### ISSUE TITLE
Add dark mode to the docs site

### ISSUE THREAD

**Issue by eliutgon** [eliutgon/buzz-notify#6]
Now looks like that...

![buzz-notify-henna vercel app_](https://user-images.githubusercontent.com/63687573/135722993-07c99075-9b4a-4bb7-bf33-4308c8fd4592.png)

**Comment by RajMhatre20** [comment]
I would like to work on this issue

**Comment by eliutgon** [comment]
Hi @RajMhatre20 

Perfect, all yours!
